### ISSUE TITLE
Failing tests on dev master

### ISSUE THREAD

**Issue by ksheedlo** [rackerlabs/mimic#452]
This is at SHA 094184f7053ac2fd62ca0280afd1dade1643f87d with a fresh `python_env` and `tox`. I don't know how I got my working tree this way, but it's frustrating that I can't get these tests to pass and therefore can't check coverage locally.

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/ken/rackerlabs/mimic/mimic/test/test_server_images.py", line 92, in test_get_image_list_with_details

  File "/Users/ken/rackerlabs/mimic/.tox/py27/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 437, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 744, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 726, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [u'OS-EXT-IMG-SIZE:size', u'co... != ['OS-DCF:diskConfig', 'OS-EXT-...

First differing element 0:
OS-EXT-IMG-SIZE:size
OS-DCF:diskConfig

+ ['OS-DCF:diskConfig',
- [u'OS-EXT-IMG-SIZE:size',
? ^^

+  'OS-EXT-IMG-SIZE:size',
? ^

-  u'com.rackspace__1__ui_default_show',
-  u'created',
?  -

+  'created',
-  u'id',
?  -

+  'id',
-  u'links',
?  -

+  'links',
-  u'metadata',
?  -

+  'metadata',
-  u'minDisk',
?  -

+  'minDisk',
-  u'minRam',
?  -

+  'minRam',
-  u'name',
?  -

+  'name',
-  u'progress',
?  -

+  'progress',
-  u'status',
?  -

+  'status',
-  u'updated']
?  -

+  'updated']

mimic.test.test_server_images.NovaAPIImagesTests.test_get_image_list_with_details
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/ken/rackerlabs/mimic/mimic/test/test_server_images.py", line 63, in test_get_server_image

  File "/Users/ken/rackerlabs/mimic/mimic/test/test_server_images.py", line 35, in get_server_image

  File "/Users/ken/rackerlabs/mimic/.tox/py27/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 437, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 200 != 404

mimic.test.test_server_images.NovaAPIImagesTests.test_get_server_image
-------------------------------------------------------------------------------
Ran 525 tests in 6.086s

FAILED (failures=2, successes=523)
```

**Comment by ksheedlo** [comment]
I solved this by blowing away my local tree and cloning again.
